server:
  port: 10006

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.155:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: mt
          uri: lb://spider-mt-server
          predicates:
            - Path=/mt/**
          #filters:
            #- StripPrefix=1