server:
  port: 18300
  undertow:
    threads:
      io: 4
      worker: 20
    buffer-size: 1024
    direct-buffers: true

spring:
  #redis配置
  redis:
    database: 2
    host: 172.19.196.113
    port: 6379
    password: wxay2020@)@)
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #输出时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

